<?php

namespace Database\Seeders;

use App\Models\Pegawai;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pegawai = [
            //1
            [   
                'nip' => '19630916 199203 1 011',       
                'nama' => 'Drs. H.  MAHYUDIN, M.Pd.',    
                't_lahir' => 'Kandangan',
                'tgl_lahir' => '1963-09-16',
                'alamat' => 'Komplek Haur Kuning Permai',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085349760026',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '15',
                'jabatan_id' => '1',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '15',
                'gaji' => '5431900',
                'naik_berkala' => '2023-05-15',
                'naik_pangkat' => '2024-05-15',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1992-03-17',
                'email' => 'aini@gmail.com ',
                'pelatihan' => 'Belum Ada',               
            ],
            //2
            [   
                'nip' => '19670127 198711 1 001',
                'nama' => 'H. NOOR FRAJI, S.Sos',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1967-01-27',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085349760088',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '12',
                'jabatan_id' => '2',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '12',
                'gaji' => '4797000',
                'naik_berkala' => '2023-05-14',
                'naik_pangkat' => '2024-05-14',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1998-03-17',
                'email' => 'raji@gmail.com',
                'pelatihan' => 'Diklat Fungsional',               
            ],
            //3
            [   
                'nip' => '19641012 198303 1 004',
                'nama' => 'Drs. FAHMI',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1964-10-12',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-Laki',
                'nohp' => '085349760077',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '13',
                'jabatan_id' => '6',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '13',
                'gaji' => '5000000',
                'naik_berkala' => '2023-08-12',
                'naik_pangkat' => '2024-10-15',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1998-04-17',
                'email' => 'fahmi@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //4
            [   
                'nip' => '199211062015071001',
                'nama' => 'MUHAMMAD LATHIEF, S. STP',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1992-11-06',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085349760079',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '11',
                'jabatan_id' => '8',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '11',
                'gaji' => '4602400',
                'naik_berkala' => '2023-08-12',
                'naik_pangkat' => '2024-08-12',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-04-17',
                'email' => 'latif@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
           //5
            [
            'nip' => '19650505 198602 1 004',
                'nama' => 'SLAMET BUDIONO, S.IP.',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1995-05-05',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085349760179',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '13',
                'jabatan_id' => '9',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '13',
                'gaji' => '5000000',
                'naik_berkala' => '2024-08-12',
                'naik_pangkat' => '2025-08-12',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-04-18',
                'email' => 'budi@gmail.com',
                'pelatihan' => 'Belum Ada',   
            ],
            //6
            [   
                'nip' => '198007262008011013',
                'nama' => 'ANANG DIDI RISWANDI, SE',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1980-07-26',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085359760179',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '12',
                'jabatan_id' => '10',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '12',
                'gaji' => '4797000',
                'naik_berkala' => '2025-07-12',
                'naik_pangkat' => '2026-08-15',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-04-16',
                'email' => 'didi@gmail.com',
                'pelatihan' => 'Diklat Fungsional',               
            ],
            //7
            [   
                'nip' => '19690818 200003  1005',
                'nama' => 'RIF`AT, S.Sos',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1969-08-18',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085259760179',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '12',
                'jabatan_id' => '11',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '12',
                'gaji' => '4602400',
                'naik_berkala' => '2023-05-12',
                'naik_pangkat' => '2025-07-12',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-04-18',
                'email' => 'rifat@gmail.com',
                'pelatihan' => 'Diklat Fungsional',                
            ],
            //8
            [   
                'nip' => '19830201 201001 1 018',
                'nama' => 'YANDRA, SE',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1983-02-01',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08115560102',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '11',
                'jabatan_id' => '3',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '12',
                'gaji' => '4797000',
                'naik_berkala' => '2023-05-12',
                'naik_pangkat' => '2024-05-12',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1998-04-18',
                'email' => 'yandra@gmail.com',
                'pelatihan' => 'Belum Ada',                 
            ],
            //9
            [   
                'nip' => '19710913 198911 1 001',
                'nama' => 'ISMAIL, SE',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1971-09-13',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08115555102',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '11',
                'jabatan_id' => '4',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '11',
                'gaji' => '4602400',
                'naik_berkala' => '2023-10-12',
                'naik_pangkat' => '2024-12-14',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1997-10-12',
                'email' => 'ismail@gmail.com',
                'pelatihan' => 'Belum Ada',                 
            ],
            //10
            [   
                'nip' => '19820515 200604 1 017',
                'nama' => 'IDI AMIN AZIS, SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1982-05-15',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08115554402',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '11',
                'jabatan_id' => '12',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '11',
                'gaji' => '4602400',
                'naik_berkala' => '2024-12-14',
                'naik_pangkat' => '2025-11-15',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-05-20',
                'email' => 'azis@gmail.com',
                'pelatihan' => 'Dilklat Prajabatan',                 
            ],
            //11
            [   
                'nip' => '19731020 200604 1 006',
                'nama' => 'SURIANI, S.AP',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1973-10-20',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08115554400',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '11',
                'jabatan_id' => '13',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '11',
                'gaji' => '4602400',
                'naik_berkala' => '2024-05-13',
                'naik_pangkat' => '2025-06-17',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1998-06-18',
                'email' => 'Suria@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //12
            [   
                'nip' => '19680402 200701 1 055',
                'nama' => 'SYAHRANI, SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1968-04-02',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08115234400',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '10',
                'jabatan_id' => '14',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '10',
                'gaji' => '4415600',
                'naik_berkala' => '2024-12-16',
                'naik_pangkat' => '2025-10-16',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-12-15',
                'email' => 'syahrani@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //13
            [   
                'nip' => '19830908 200604 1 004',
                'nama' => 'NADIANSYAH, SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1983-09-08',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08115265400',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '10',
                'jabatan_id' => '15',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '10',
                'gaji' => '4415600',
                'naik_berkala' => '2024-12-17',
                'naik_pangkat' => '2025-10-18',
                'sts_pegawai' => 'Aktif',
                'tmt' => '2000-12-15',
                'email' => 'nadi@gmail.com',
                'pelatihan' => 'Diklat Dalam Jabatan',               
            ],
            //14
            [   
                'nip' => '19720110 200003 1 002',
                'nama' => 'JAYA PRIATNA',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1972-01-10',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08111234400',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '10',
                'jabatan_id' => '16',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '10',
                'gaji' => '4415600',
                'naik_berkala' => '2024-12-16',
                'naik_pangkat' => '2025-10-16',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-12-15',
                'email' => 'jaya@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //15
            [   
                'nip' => '19750214 200604 1 011',
                'nama' => 'RAHMATULLAH SUGIANTO, SM',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1975-02-14',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '08111324400',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '17',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '3373600',
                'naik_berkala' => '2024-12-16',
                'naik_pangkat' => '2025-10-16',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-11-12',
                'email' => 'rahmat@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //16
            [   
                'nip' => '19800701 200604 1 016',
                'nama' => 'FITRIANSYAH, SM',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1980-07-01',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082150133000',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '18',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '3373600',
                'naik_berkala' => '2024-05-12',
                'naik_pangkat' => '2025-04-05',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-11-06',
                'email' => 'jojon@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //17
            [   
                'nip' => '19950504 202012 1 007',
                'nama' => 'M.BUYUNG RAHMATILLAH, SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1995-05-04',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082155133000',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '19',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '3373600',
                'naik_berkala' => '2024-05-05',
                'naik_pangkat' => '2025-11-15',
                'sts_pegawai' => 'Aktif',
                'tmt' => '2001-11-06',
                'email' => 'buyung@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //18
            [   
                'nip' => '19720507 199303 1 010',
                'nama' => 'KARTIMAN, S., SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1972-05-07',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151133000',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '10',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '10',
                'gaji' => '4415600',
                'naik_berkala' => '2024-08-19',
                'naik_pangkat' => '2025-10-15',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1998-02-20',
                'email' => 'karti@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //19
            [   
                'nip' => '19770210 200604 1 008',
                'nama' => 'AMAT PADELI, S. Ak.',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1977-02-10',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151134500',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '20',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2024-08-19',
                'naik_pangkat' => '2026-08-19',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1996-02-15',
                'email' => 'amat@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //20
            [   
                'nip' => '19690210 2006041 016',
                'nama' => 'YUNANI',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1969-02-10',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151224500',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '21',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-08-19',
                'naik_pangkat' => '2027-08-19',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1997-02-20',
                'email' => 'yunani@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //21
            [   
                'nip' => '19710114 200604 1 001',
                'nama' => 'BASUKI RAHMAT',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1971-01-14',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151289500',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '22',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2023-06-17',
                'naik_pangkat' => '2024-08-19',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1999-10-15',
                'email' => 'abas@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //22
            [   
                'nip' => '19770413 200604 1 014',
                'nama' => 'NARUDIN JANGKI, SH.',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1977-04-13',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151659500',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2024-09-08',
                'naik_pangkat' => '2025-07-20',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1998-09-09',
                'email' => 'jangki@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //23
            [   
                'nip' => '19780430 200604 1 011',
                'nama' => 'MAULANA AKHMAD RIZA H',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1978-04-30',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151659599',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2024-09-09',
                'naik_pangkat' => '2025-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1997-02-10',
                'email' => 'riza@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //24
            [   
                'nip' => '19710817 200604 1 026',
                'nama' => 'ROBI CAHYADI',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1971-08-17',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151569599',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2024-09-09',
                'naik_pangkat' => '2025-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1996-02-10',
                'email' => 'robi@gmail.com',
                'pelatihan' => 'Diklat prajabata',               
            ],
            //25
            [   
                'nip' => '19791108 200604 1 022',
                'nama' => 'MUKHLIS, SH.',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1979-11-08',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151561299',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-09-09',
                'naik_pangkat' => '2027-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1996-02-10',
                'email' => 'muhklis@gmail.com',
                'pelatihan' => 'Diklat dalam jabatan',               
            ],
            //26
            [   
                'nip' => '19730129 200604 1 009',
                'nama' => 'MUHAMMAD MAHDIANSYAH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1973-01-29',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085351561299',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2025-09-09',
                'naik_pangkat' => '2026-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1995-02-10',
                'email' => 'mahdi@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //27
            [   
                'nip' => '19821210 200501 1 005',
                'nama' => 'MARPASI',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1982-12-10',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '081251561299',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '6',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-09-09',
                'naik_pangkat' => '2027-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1995-02-10',
                'email' => 'marpasi@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //28
            [   
                'nip' => '19871220 202012 1 002',
                'nama' => 'ANDRI SURYA WARDANA, SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1987-12-20',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '081251571299',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '23',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-09-09',
                'naik_pangkat' => '2027-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1994-02-10',
                'email' => 'andri2@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //29
            [   
                'nip' => '19880531 202012 1 003',
                'nama' => 'ANDY KRISTANTO, SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1988-08=31',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082351571299',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '23',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-09-09',
                'naik_pangkat' => '2027-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1995-02-10',
                'email' => 'andy09@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //30
            [   
                'nip' => '19880608 202012 1 003',
                'nama' => 'ADITYA SAPUTRA, SH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1988-06-08',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082151571299',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '23',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2027-09-09',
                'naik_pangkat' => '2028-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1995-02-10',
                'email' => 'saputra2@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //31
            [   
                'nip' => '19890710 202012 2 007',
                'nama' => 'SITI SAMIAH, SH',
                't_lahir' => 'Banjarmasin',
                'tgl_lahir' => '1989-07-10',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Perempuan',
                'nohp' => '085754098197',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '23',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2027-09-09',
                'naik_pangkat' => '2028-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1995-02-10',
                'email' => 'samiah@gmail.com',
                'pelatihan' => 'Diklat dalam Jabatan',               
            ],
            //32
            [   
                'nip' => '19890312 202012 1 002',
                'nama' => 'RENDY HIDAYAT, SE',
                't_lahir' => 'Banjarmasin',
                'tgl_lahir' => '1989-03-12',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '088954098197',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '7',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2027-09-09',
                'naik_pangkat' => '2028-07-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1997-02-10',
                'email' => 'rendy00@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //33
            [   
                'nip' => '19920707 202012 2 012',
                'nama' => 'ZAKIAH, S.Sos',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1999-07-07',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Perempuan',
                'nohp' => '085454098197',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '24',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2027-06-09',
                'naik_pangkat' => '2028-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '2001-02-10',
                'email' => 'zakiah@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //34
            [   
                'nip' => '19700622 200604 1 006',
                'nama' => 'ARIF JOHANSYAH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1970-06-22',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '085454098227',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '25',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2027-06-09',
                'naik_pangkat' => '2028-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1994-02-10',
                'email' => 'arif@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //35
            [   
                'nip' => '19830319 200604 2 012',
                'nama' => 'KHATIMAH',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1983-03-19',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Perempuan',
                'nohp' => '081264098227',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '25',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2027-06-09',
                'naik_pangkat' => '2028-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1993-02-10',
                'email' => 'khatimah@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //36
            [   
                'nip' => '19720825 200604 1 014',
                'nama' => 'AHMAD NOOR',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1972-08-25',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '081264098297',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-06-09',
                'naik_pangkat' => '2027-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1993-02-10',
                'email' => 'noor02@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //37
            [   
                'nip' => '19740727 200604 1 016',
                'nama' => 'RIZALI',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1974-07-27',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082164098297',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-06-09',
                'naik_pangkat' => '2027-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1992-02-10',
                'email' => 'rizal1@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //38
            [   
                'nip' => '19820502 200604 1 015',
                'nama' => 'MUHAMMAD ALI',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1982-05-02',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '082364098297',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-06-09',
                'naik_pangkat' => '2027-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1992-02-10',
                'email' => 'ali@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //39
            [   
                'nip' => '197707102006041034',
                'nama' => 'PARANCIS',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '197-07-10',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '081564098297',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '9',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '9',
                'gaji' => '4236400',
                'naik_berkala' => '2026-06-09',
                'naik_pangkat' => '2027-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1993-02-10',
                'email' => 'parancis@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //40
            [   
                'nip' => '19700530 201212 1 004',
                'nama' => 'MAULANA',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1970-07-10',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '081564098297',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '7',
                'jabatan_id' => '22',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '7',
                'gaji' => '3665000',
                'naik_berkala' => '2026-06-09',
                'naik_pangkat' => '2027-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1989-02-10',
                'email' => 'maulana@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
            //41
            [   
                'nip' => '19650112 200701 1 032',
                'nama' => 'PARSI',
                't_lahir' => 'Rantau',
                'tgl_lahir' => '1965-01-12',
                'alamat' => 'Rantau',
                'j_kelamin' => 'Laki-laki',
                'nohp' => '081504098297',
                'agama' => 'Islam',
                'sts_kawin' => 'Menikah',
                'pendidikan' => 'S2',
                'jumlah_anak' => '2',
                'pangkat_id' => '6',
                'jabatan_id' => '26',
                'masa_kerja' => '30 Tahun',
                'golongan_id' => '6',
                'gaji' => '3516000',
                'naik_berkala' => '2027-06-09',
                'naik_pangkat' => '2028-04-08',
                'sts_pegawai' => 'Aktif',
                'tmt' => '1988-02-10',
                'email' => 'parsi@gmail.com',
                'pelatihan' => 'Belum Ada',               
            ],
          ];     
        
          foreach($pegawai as $key => $value){
            Pegawai::create($value);
          }
    }
    
}
